FROM node:16 AS builder

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY prisma ./prisma/

# Install app dependencies
RUN npm install --legacy-peer-deps

ADD . .

FROM node:16


RUN mkdir /app
WORKDIR /app

ADD . /app

COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package*.json /app/
COPY --from=builder /app/prisma /app/prisma

EXPOSE 3000
CMD ["npm", "run", "migrate:start:dev" ]
# CMD ["node", "node_modules/.bin/remix", "dev"]
