version: "3.9"

services:
  graphql:
    build:
      context: ../../
      dockerfile: ./services/graphql/Dockerfile
    environment:
      - PORT=8080
      - PANO_API_URL=http://pano-api:8080
    ports:
      - "8000:8080"
    networks:
      - kampus

networks:
  kampus:
    name: kampus
