version: "3.9"

services:
  pano-api:
    build:
      context: ../../
      dockerfile: ./services/pano-api/Dockerfile
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://pgtest:pgtest@postgres:5432/pgtest
    ports:
      - "8110:8080"
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kampus

  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=pgtest
      - POSTGRES_DB=pgtest
      - POSTGRES_PASSWORD=pgtest
    networks:
      - kampus
    healthcheck:
      test: pg_isready -U pgtest -d pgtest
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@kamp.us
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_LOG_LEVEL=50
    networks:
      - kampus
    ports:
      - "8090:80"
    links:
      - postgres
    logging:
      driver: "none"
    volumes:
      - ./scripts/servers.json:/pgadmin4/servers.json

networks:
  kampus:
    name: kampus
