version: "3.3"
services:
  app:
    build:
      context: ../../
      dockerfile: ./apps/pano/Dockerfile.dev
    entrypoint: ["turbo", "run", "docker", "--scope=@kampus-apps/pano"]
    ports:
      - "3000:3000"
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://pgtest:pgtest@postgres:5432/pgtest?schema=public&connect_timeout=300
      - SESSION_SECRET=sessionsecret
      - NODE_ENV=development
    volumes:
      - ./src:/app/apps/pano/src
      - ./prisma:/app/apps/pano/prisma
      - ./public:/app/apps/pano/public
      - ./remix.config.js:/app/apps/pano/remix.config.js
      - ./tsconfig.json:/app/apps/pano/tsconfig.json
    networks:
      - pano
    depends_on:
      - postgres
  postgres:
    # match the version to the RDS
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=pgtest
      - POSTGRES_DB=pgtest
      - POSTGRES_PASSWORD=pgtest
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5555:5432"
    healthcheck:
      test: pg_isready -U pgtest -d pgtest
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - pano
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
networks:
  pano:
