FROM node:16

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
# Install app dependencies
RUN npm install

COPY prisma ./prisma/

RUN npx prisma generate

ADD . .

EXPOSE 3000

ENTRYPOINT ["npm", "run", "docker"]
