export const streamers = [
  { username: "usirin" },
  { username: "cansirin" },
  { username: "alicangunduzdev" },
  { username: "corefunctionsinitiated" },
  { username: "geeksofdata" },
  { username: "notdepressedeveloper" },
  { username: "wykonos" },
  { username: "teachmejs" },
  { username: "berankeday" },
  { username: "harami" },
  { username: "ozzy_efe" },
  { username: "devshackle" },
  { username: "mehmetcantasdev" },
  { username: "iatee" },
  { username: "thebeastofthemiddleeast" },
  { username: "devketchuptv" },
  { username: "creosb" },
  { username: "berkaycodes" },
];
